# Generated by Django 5.0.6 on 2024-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_age_remove_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
